BASE_TASK_CONFIG_PATH: "configs/semantic_audionav/savi/mp3d/semantic_audiogoal_distractor.yaml"
TRAINER_NAME: "ddppo"
NUM_PROCESSES: 8
SENSORS: ["DEPTH_SENSOR", "RGB_SENSOR"]
NUM_UPDATES: 20000
LOG_INTERVAL: 10
CHECKPOINT_INTERVAL: 50
VIDEO_OPTION: []
VISUALIZATION_OPTION: []

EVAL:
  SPLIT: "val"
  USE_CKPT_CONFIG: True

RL:
  PPO:
    clip_param: 0.2
    ppo_epoch: 2
    num_mini_batch: 2
    value_loss_coef: 0.5
    entropy_coef: 0.05
    lr: 2.5e-4
    eps: 1e-5
    max_grad_norm: 0.2
    # decide the length of history that ppo encodes
    num_steps: 150
    hidden_size: 512
    use_gae: True
    gamma: 0.99
    tau: 0.95
    use_linear_clip_decay: False
    use_linear_lr_decay: False
    # window size for calculating the past rewards
    reward_window_size: 50
    use_normalized_advantage: False
    policy_type: "smt"
    use_belief_predictor: True
    use_external_memory: True
    SCENE_MEMORY_TRANSFORMER:
      memory_size: 1
      hidden_size: 256
      nhead: 8
      num_encoder_layers: 1
      num_decoder_layers: 1
      dropout: 0.0
      activation: 'relu'
      use_pretrained: False
      pretrained_path: ''
      freeze_encoders: False
      pretraining: True
    BELIEF_PREDICTOR:
      online_training: True
      train_encoder: False
      lr: 1e-3
      use_label_belief: True
      use_location_belief: True
  DDPPO:
    sync_frac: 0.6
    distrib_backend: "GLOO"
    rnn_type: "GRU"
    num_recurrent_layers: 1
    backbone: "custom_resnet18"
    pretrained_weights: ""
    pretrained: False
    reset_critic: False