ENVIRONMENT:
  MAX_EPISODE_STEPS: 500
SIMULATOR:
  HABITAT_SIM_V0:
    GPU_DEVICE_ID: 0
  RGB_SENSOR:
    WIDTH: 128
    HEIGHT: 128
  DEPTH_SENSOR:
    WIDTH: 128
    HEIGHT: 128

  TYPE: "SoundSpacesSim"
  ACTION_SPACE_CONFIG: "v0"
  SCENE_DATASET: "mp3d"
  GRID_SIZE: 1.0
  AUDIO:
    EVERLASTING: False
    RIR_SAMPLING_RATE: 16000
    SOURCE_SOUND_DIR: "data"

TASK:
  TYPE: SemanticAudioNav

  SENSORS: ['AUDIOGOAL_SENSOR', 'SPECTROGRAM_SENSOR', 'CATEGORY', 'POINTGOAL_WITH_GPS_COMPASS_SENSOR', 'POSE_SENSOR', 'LOCATION_BELIEF', 'CATEGORY_BELIEF']
  GOAL_SENSOR_UUID: spectrogram
  POINTGOAL_WITH_GPS_COMPASS_SENSOR:
    GOAL_FORMAT: "CARTESIAN"
    DIMENSIONALITY: 2

  MEASUREMENTS: ['DISTANCE_TO_GOAL', 'NORMALIZED_DISTANCE_TO_GOAL', 'SUCCESS', 'SPL', 'SOFT_SPL', 'NUM_ACTION', 'SUCCESS_WEIGHTED_BY_NUM_ACTION', 'SUCCESS_WHEN_SILENT']
  SPL:
    TYPE: SPL
  TOP_DOWN_MAP:
    MAP_RESOLUTION: 10000
    DRAW_BORDER: True
    DRAW_SHORTEST_PATH: True
  DISTANCE_TO_GOAL:
    DISTANCE_TO: VIEW_POINTS

DATASET:
  TYPE: "SemanticAudioNav"
  SPLIT: "train_seen-scenes_heard-sounds"
  CONTENT_SCENES: ["*"]
  VERSION: 'v1'
  SCENES_DIR: "data/scene_datasets/mp3d"
  DATA_PATH: "data/datasets/semantic_aven/mp3d/{version}/{split}/{split}.json.gz"
